### PR TITLE
Updated insert_validator and other minor changes

### PR DESCRIPTION
**Pull request by ericecook**
removed unnecessary test.js
added css vars for button
added a node for block button

### CODE REVIEW

**Comment by icook** [comment]
I believe the ButtonNode is somewhat a relic of very early dev days. Is there even a reason to have one that doesn't extend the BaseNode?

**Comment by ericecook** [comment]
Not that I'm aware of, I didn't know if you were using it for something though so I didn't want to outright remove it.

**Comment by ericecook** [comment]
Gonna merge this in if it looks good enough to you

**Comment by icook** [comment]
What about the note on the redirection? It's really not usable at this moment in time is it? (https://github.com/icook/yota/pull/53/files#L0R29)

**Comment by ericecook** [comment]
Depends on how you define usable lol. It's functional, just not pretty. But yea that'd be good to take care of now probably.

I'll push up a commit in a while moving it to the success render

**Comment by icook** [comment]
Haha. Optionally you could just pull it out so I can merge this. Either or.

**Comment by ericecook** [comment]
redirect functionality is pretty subject to change at this point

**Pull request merged**
